Repository elastic/go-elasticsearch, pull requests merged in 2023-11, with the labels that each got.

#745 CI: Update skiplist to remove expansion search missing ml node
  internal/build/cmd/generate/commands/gentests/skips.go
Labels: backport 8.11

#751 [DOCS] Adds context selector widget to the getting started page
  .doc/getting-started.asciidoc
  .doc/tab-widgets/connecting-widget.asciidoc
  .doc/tab-widgets/connecting.asciidoc
  .doc/tab-widgets/create-index-widget.asciidoc
  .doc/tab-widgets/create-index.asciidoc
  .doc/tab-widgets/delete-documents-widget.asciidoc
  .doc/tab-widgets/delete-documents.asciidoc
  .doc/tab-widgets/delete-index-widget.asciidoc
  .doc/tab-widgets/delete-index.asciidoc
  .doc/tab-widgets/get-documents-widget.asciidoc
  .doc/tab-widgets/get-documents.asciidoc
  .doc/tab-widgets/index-document-widget.asciidoc
  .doc/tab-widgets/index-document.asciidoc
  .doc/tab-widgets/search-documents-widget.asciidoc
  .doc/tab-widgets/search-documents.asciidoc
  .doc/tab-widgets/update-documents-widget.asciidoc
  .doc/tab-widgets/update-documents.asciidoc
Labels: documentation

#753 [8.11][DOCS] Adds context selector widget to the getting started page
  .doc/getting-started.asciidoc
  .doc/tab-widgets/connecting-widget.asciidoc
  .doc/tab-widgets/connecting.asciidoc
  .doc/tab-widgets/create-index-widget.asciidoc
  .doc/tab-widgets/create-index.asciidoc
  .doc/tab-widgets/delete-documents-widget.asciidoc
  .doc/tab-widgets/delete-documents.asciidoc
  .doc/tab-widgets/delete-index-widget.asciidoc
  .doc/tab-widgets/delete-index.asciidoc
  .doc/tab-widgets/get-documents-widget.asciidoc
  .doc/tab-widgets/get-documents.asciidoc
  .doc/tab-widgets/index-document-widget.asciidoc
  .doc/tab-widgets/index-document.asciidoc
  .doc/tab-widgets/search-documents-widget.asciidoc
  .doc/tab-widgets/search-documents.asciidoc
  .doc/tab-widgets/update-documents-widget.asciidoc
  .doc/tab-widgets/update-documents.asciidoc
Labels: documentation

#758 [DOCS] Adds a signpost for downloading ES or signing-up for ESS
  README.md
Labels: documentation, backport 8.11

#762 [Changelog] Add 8.11.1 release
  CHANGELOG.md
Labels: backport 8.11
