Repository elastic/go-elasticsearch, pull requests merged in 2023-03, with the labels that each got.

#623 Do not drop item after flush() failed
  esutil/bulk_indexer.go
Labels: bug

#627 [TypedClient] Rename Request interface method following API changes
  typedapi/typedclient.request.go
Labels: backport 8.7

#631 [DOCS] Creates custom landing page for the Go client book
  .doc/index-custom-title-page.html
Labels: documentation, backport 8.7

#636 [CI] Update TLS certificates
  .ci/certs/testnode.crt
  .ci/certs/testnode.key
  elasticsearch_internal_test.go
Labels: backport 8.7

#638 Transport: Bump to latest main version 1a3c63d
  go.mod
  go.sum
Labels: backport 8.7

#642 [DOCS] Changes hero image on the landing page and adds a line about license
  .doc/index-custom-title-page.html
Labels: documentation, backport 8.7

#644 Changelog for 8.7.0 release
  CHANGELOG.md
Labels: backport 8.7
