Repository elastic/go-elasticsearch, pull requests merged in 2024-06, with the labels that each got.

#866 [Dependency] remove golint
  .buildkite/Dockerfile
  .ci/Dockerfile
  .github/workflows/build.yml
  Makefile
Labels: backport 8.14

#870 [Transport] Bump to v8.6.0
  _examples/bulk/benchmarks/go.mod
  _examples/bulk/benchmarks/go.sum
  _examples/bulk/go.sum
  _examples/bulk/kafka/go.mod
  _examples/bulk/kafka/go.sum
  _examples/cloudfunction/go.sum
  _examples/encoding/go.sum
  _examples/fasthttp/go.sum
  _examples/go.mod
  _examples/go.sum
  _examples/instrumentation/go.sum
  _examples/logging/go.sum
  _examples/security/go.sum
  _examples/xkcdsearch/go.sum
  go.mod
  go.sum
  internal/build/go.mod
  internal/build/go.sum
  internal/testing/go.mod
  internal/testing/go.sum
Labels: backport 8.14

#872 [Changelog] Add 8.14.0
  CHANGELOG.md
Labels: backport 8.14

#860 [DOCS] Add ES|QL doc structure
  .doc/index.asciidoc
  .doc/typedapi/esql.asciidoc
  .doc/typedapi/index.asciidoc
Labels: documentation, backport 8.14

#878 Rename Buildkite team from clients-team to devtools-team
  catalog-info.yaml
Labels: backport 8.13, backport 8.14
