Repository elastic/go-elasticsearch, pull requests merged in 2024-11, with the labels that each got.

#918 bump changelog to 8.16
  CHANGELOG.md
Labels: backport 8.16, backport 8.x

#917 Bump go.mod toolchain to 1.22.0
  esapi/test/go.mod
  internal/build/go.mod
Labels: backport 8.16

#914 Expose BulkIndexer total flushed bytes metric
  esutil/bulk_indexer.go
Labels: backport 8.15, backport 8.16, backport 8.x, backport 8.17
