Repository elastic/go-elasticsearch, pull requests merged in 2024-02, with the labels that each got.

#797 Fix ticker memory leak in bulk indexer due to internal flush call resetting the ticker
  esutil/bulk_indexer.go
Labels: backport 8.12

#794 Update connecting.asciidoc to use ‘os’ instead of deprecated ‘ioutil’
  .doc/connecting.asciidoc
Labels: backport 8.12

#793 Fix indentation issues in indexing.asciidoc
  .doc/typedapi/examples/indexing.asciidoc
Labels: backport 8.12

#804 [Examples] bump dependencies
  _examples/bulk/Makefile
  _examples/bulk/benchmarks/go.mod
  _examples/bulk/benchmarks/go.sum
  _examples/bulk/go.sum
  _examples/bulk/kafka/go.mod
  _examples/bulk/kafka/go.sum
  _examples/cloudfunction/go.sum
  _examples/encoding/go.sum
  _examples/fasthttp/go.sum
  _examples/instrumentation/go.mod
  _examples/instrumentation/go.sum
  _examples/logging/go.sum
  _examples/security/go.sum
  _examples/xkcdsearch/go.sum
Labels: backport 8.12, backport 8.13

#807 [Internal] bump dependencies for generator & tests
  esapi/test/go.mod
  go.sum
  internal/build/go.mod
  internal/build/go.sum
Labels: backport 8.12, backport 8.13

#810 [Skip list] update for 8.12
  internal/build/cmd/generate/commands/gentests/skips.go
Labels: backport 8.12, backport 8.13

#813 [Changelog] Add 8.12.1
  CHANGELOG.md
Labels: backport 8.12, backport 8.13

#816 [DOCS] Adds compatibility matrix to docs
  .doc/installation.asciidoc
Labels: documentation, backport 8.12, backport 8.13
