Repository elastic/go-elasticsearch, pull requests merged in 2025-04, with the labels that each got.

#974 [Docs] Remove stale serverless page
  docs/reference/getting-started-serverless.md
  docs/reference/toc.yml
Labels: documentation

#981 Transport: Bump to 8.7.0
  _benchmarks/benchmarks/go.mod
  _examples/bulk/benchmarks/go.mod
  _examples/bulk/benchmarks/go.sum
  _examples/bulk/go.mod
  _examples/bulk/go.sum
  _examples/bulk/kafka/go.mod
  _examples/bulk/kafka/go.sum
  _examples/cloudfunction/go.mod
  _examples/cloudfunction/go.sum
  _examples/configuration.go
  _examples/encoding/go.mod
  _examples/encoding/go.sum
  _examples/extension/go.mod
  _examples/extension/go.sum
  _examples/fasthttp/go.mod
  _examples/fasthttp/go.sum
  _examples/go.mod
  _examples/go.sum
  _examples/instrumentation/go.mod
  _examples/instrumentation/go.sum
  _examples/logging/go.mod
  _examples/logging/go.sum
  _examples/security/go.mod
  _examples/security/go.sum
  _examples/xkcdsearch/go.mod
  _examples/xkcdsearch/go.sum
  go.mod
  go.sum
  internal/testing/go.mod
  internal/testing/go.sum
Labels: backport 8.x, backport 8.18, backport 9.0

#986 Generator: exclude deprecated knn_search endpoint for v9
  internal/build/cmd/generate/commands/gensource/command.go
Labels: backport 9.0

#990 Feat: Add constructor for baseclient
  elasticsearch.go
  internal/build/cmd/generate/commands/gensource/generator.go
Labels: backport 8.x, backport 8.18, backport 9.0

#1007 [docs] Fix various syntax and rendering errors
  docs/reference/_getting_started_with_the_api.md
Labels: documentation
